<a href="https://colab.research.google.com/github/bishalanimates-stack/5CS037/blob/main/BishalSaud_Worksheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [2]:
# Task 1: Create an empty 2x2 array
empty_arr = np.empty((2,2))
empty_arr


array([[2.74598556e-315, 0.00000000e+000],
       [3.31971956e-316, 2.72513895e-315]])

In [3]:
# Task 2: Create 4x2 array of ones
ones_arr = np.ones((4,2))
ones_arr


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [4]:
# Task 3: Create 3x3 array filled with a constant value
full_arr = np.full((3,3), 9)
full_arr



array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

In [5]:

# Task 4: Create zeros_like() from an existing array
base = np.array([[1,2,3],[4,5,6]])
zeros_like_arr = np.zeros_like(base)
zeros_like_arr


array([[0, 0, 0],
       [0, 0, 0]])

In [6]:

# Task 5: Create ones_like() from an existing array
ones_like_arr = np.ones_like(base)
ones_like_arr



array([[1, 1, 1],
       [1, 1, 1]])

In [7]:
# Task 6: Convert a Python list to numpy array
new_list = [1,2,3,4]
converted_arr = np.array(new_list)
converted_arr

array([1, 2, 3, 4])

In [8]:
# Task 1: Create array from 10 to 49
arr_10_49 = np.arange(10, 50)
arr_10_49


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [9]:

# Task 2: Create 3x3 matrix with values 0-8
matrix_0_8 = np.arange(9).reshape(3,3)
matrix_0_8

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
# Task 3: Create 3x3 identity matrix
identity_3 = np.eye(3)
identity_3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
# Task 4: Random array of size 30 + mean
rand30 = np.random.random(30)
rand30_mean = rand30.mean()
rand30_mean

np.float64(0.5322206846737365)

In [12]:
# Task 5: Create 10x10 random array + find min & max
rand_10x10 = np.random.random((10,10))
rand_min = rand_10x10.min()
rand_max = rand_10x10.max()
rand_min, rand_max

(np.float64(0.026135225723510014), np.float64(0.994591936674755))

In [13]:
# Task 6: Zero array of size 10, replace 5th element with 1
zero_arr = np.zeros(10)
zero_arr[4] = 1
zero_arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [14]:
# Task 7: Reverse elements of an array
arr = np.array([1,2,0,0,4,0])
rev_arr = arr[::-1]
rev_arr

array([0, 4, 0, 0, 2, 1])

In [16]:
# Task 8: Create 5x5 matrix with border=1 and inside=0
border = np.ones((5,5))
border[1:-1, 1:-1] = 0
border

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
# Task 9: Create 8x8 checkerboard pattern
checker = np.zeros((8,8))
checker[1::2, ::2] = 1
checker[::2, 1::2] = 1
checker

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [18]:
# Given arrays for operations
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

In [19]:
# Task 1: Add arrays x + y
add_xy = x + y
add_xy

array([[ 6,  8],
       [10, 13]])

In [20]:
# Task 2: Subtract arrays x - y
sub_xy = x - y
sub_xy


array([[-4, -4],
       [-4, -3]])

In [21]:
# Task 3: Multiply array x with integer
mul_x = x * 5
mul_x


array([[ 5, 10],
       [15, 25]])

In [22]:
# Task 4: Square each element of x
square_x = x**2
square_x

array([[ 1,  4],
       [ 9, 25]])

In [23]:
# Task 5: Dot products
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
dot_vw, dot_xv, dot_xy

(np.int64(219),
 array([29, 77]),
 array([[19, 22],
        [50, 58]]))

In [24]:
# Task 6: Concatenate x & y (row-wise), v & w (vertical)
concat_xy_rows = np.concatenate((x, y), axis=0)
concat_vw_cols = np.vstack((v, w))
concat_xy_rows, concat_vw_cols

(array([[1, 2],
        [3, 5],
        [5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]]))

In [25]:
# Task 7: Concat x and v (NOTE: This produces shape error)
# concat_xv = np.concatenate((x, v))  # Uncomment to see error

In [26]:
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

In [27]:
# Task 1: Show A * A^-1 = I
A_inv = np.linalg.inv(A)
identity_check = A @ A_inv
identity_check

array([[1.00000000e+00, 0.00000000e+00],
       [1.77635684e-15, 1.00000000e+00]])

In [28]:
# Task 2: Show AB != BA
AB = A @ B
BA = B @ A
AB, BA

(array([[23, 13],
        [51, 29]]),
 array([[36, 44],
        [13, 16]]))

In [29]:
# Task 3: Verify (AB)^T = B^T A^T
lhs = (A @ B).T
rhs = B.T @ A.T
lhs, rhs

(array([[23, 51],
        [13, 29]]),
 array([[23, 51],
        [13, 29]]))

In [30]:
# Task: Solve system AX=B using inverse and solve()

A = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
])

B = np.array([-1, -3, 9])

# Method 1: Using inverse
A_inv = np.linalg.inv(A)
X1 = A_inv @ B
X1

array([ 2.,  1., -2.])

In [31]:
# Method 2: Using np.linalg.solve()
X2 = np.linalg.solve(A, B)
X2

array([ 2.,  1., -2.])

In [32]:
import numpy as np
import time

In [33]:
# Python addition
list1 = list(range(1_000_000))
list2 = list(range(1_000_000))

start = time.time()
py_add = [list1[i] + list2[i] for i in range(1_000_000)]
python_add_time = time.time() - start
python_add_time

0.12123870849609375

In [34]:
# NumPy addition
np1 = np.arange(1_000_000)
np2 = np.arange(1_000_000)

start = time.time()
np_add = np1 + np2
numpy_add_time = time.time() - start
numpy_add_time

0.004418611526489258

In [35]:
# Python multiplication
start = time.time()
py_mul = [list1[i] * list2[i] for i in range(1_000_000)]
python_mul_time = time.time() - start
python_mul_time

0.12184381484985352

In [36]:
# NumPy multiplication
start = time.time()
np_mul = np1 * np2
numpy_mul_time = time.time() - start
numpy_mul_time

0.006289243698120117

In [37]:
# Python dot product
start = time.time()
py_dot = sum(list1[i] * list2[i] for i in range(1_000_000))
python_dot_time = time.time() - start
python_dot_time

0.14202499389648438

In [38]:
# NumPy dot product
start = time.time()
np_dot = np.dot(np1, np2)
numpy_dot_time = time.time() - start
numpy_dot_time


0.0022077560424804688

In [39]:
# Python matrix multiplication (very slow)
A_py = [[i for i in range(1000)] for _ in range(1000)]
B_py = [[i for i in range(1000)] for _ in range(1000)]

start = time.time()
C_py = [[sum(A_py[i][k] * B_py[k][j] for k in range(1000))
         for j in range(1000)] for i in range(1000)]
python_matmul_time = time.time() - start
python_matmul_time

186.3585560321808

In [ ]:
# NumPy fast matrix multiplication
A_np = np.arange(1_000_000).reshape(1000,1000)
B_np = np.arange(1_000_000).reshape(1000,1000)

start = time.time()
C_np = A_np @ B_np
numpy_matmul_time = time.time() - start
numpy_matmul_time
